# Generated by Django 6.0.1 on 2026-02-13 01:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas_pagar', '0011_alter_contapagar_fornecedor'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Periodicidade')),
                ('dia_vencimento', models.PositiveIntegerField(help_text='Dia do mês em que a assinatura vence (1-28)', verbose_name='Dia do Vencimento')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='empresa.empresa', verbose_name='Fornecedor')),
                ('plano_conta', models.ForeignKey(limit_choices_to={'tipo': 'conta'}, on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='contas_pagar.planodecontas', verbose_name='Plano de Contas')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
