# Generated by Django 6.0.1 on 2026-02-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='empresa.empresa'),
            preserve_default=False,
        ),
    ]
