# Generated by Django 6.0.1 on 2026-02-11 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0002_alter_contareceber_cliente'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='empresa.empresa'),
        ),
    ]
