"""
Django settings for financeiro project - DESENVOLVIMENTO LOCAL

IMPORTANTE: Este arquivo é para ambiente de DESENVOLVIMENTO.
Para produção no PythonAnywhere, use settings_2.py

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

ENVIRONMENT = os.environ.get('DJANGO_ENV', 'local').lower()
IS_PRODUCTION = ENVIRONMENT in {'prod', 'production'}

# SECURITY WARNING: keep the secret key used in production secret!
# Local dev uses a fallback key. For production/PythonAnywhere:
# - set DJANGO_ENV=production
# - set DJANGO_SECRET_KEY with a strong value
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-c&xg5cyk9k($p04+ay7=ho#cq2knt5-n#trswxhc91ajhtum6)'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Local dev defaults to DEBUG=True. For production/PythonAnywhere set:
# - DJANGO_ENV=production
# - DEBUG=False
DEBUG = os.environ.get('DEBUG', 'True' if not IS_PRODUCTION else 'False') == 'True'

# Local dev keeps only localhost; production should set ALLOWED_HOSTS explicitly.
DEFAULT_ALLOWED_HOSTS = 'localhost,127.0.0.1' if not IS_PRODUCTION else ''
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS).split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        "accounts",
        "login",
        "contas_pagar",
        "contas_receber",
        "empresa",
        "investimento"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'financeiro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'financeiro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # Sem validadores - aceita qualquer senha (até 6 dígitos)
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'pt-BR'
TIME_ZONE = 'America/Sao_Paulo' # Em vez de 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True # Mantém o uso de Timezone, mas exibe no horário de SP

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ANTES: STATIC_URL = 'static/'
# DEPOIS: Adicionado STATIC_ROOT para produção (collectstatic)
STATIC_URL = 'static/'
# For production/PythonAnywhere, collectstatic uses STATIC_ROOT.
# Keep it configured but it is mostly ignored in local dev.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AUTH_USER_MODEL = "accounts.User"

JAZZMIN_SETTINGS = {
    "site_title": "Painel Administrativo",
    "site_header": "Administração do Sistema",
    "welcome_sign": "Bem-vindo ao Painel",
    "copyright": "Seu Projeto",
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # temas: flatly, darkly, cyborg, solar, etc.
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "footer_fixed": False,
}

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "contas_pagar_lista"
