# Generated by Django 6.0.1 on 2026-02-11 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ativo', models.CharField(choices=[('acoes', 'Ações'), ('criptomoeda', 'Criptomoeda'), ('fii', 'Fundo Imobiliário'), ('renda_fixa', 'Renda Fixa'), ('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro_direto', 'Tesouro Direto'), ('debentures', 'Debêntures'), ('etf', 'ETF'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Ativo')),
                ('ticker', models.CharField(help_text='Ex: PETR4, BTCUSD, MXRF11, etc.', max_length=20, verbose_name='Ticker/Código')),
                ('nome_ativo', models.CharField(blank=True, help_text='Ex: Petrobras PN, Bitcoin, Maxi Renda FII', max_length=200, verbose_name='Nome do Ativo')),
                ('tipo_operacao', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], default='compra', max_length=10, verbose_name='Tipo de Operação')),
                ('data_operacao', models.DateField(verbose_name='Data da Operação')),
                ('quantidade', models.DecimalField(decimal_places=8, help_text='Quantidade de ativos comprados/vendidos', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=8, help_text='Preço por unidade do ativo', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='Preço Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da operação (quantidade × preço unitário)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('taxa_corretagem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxa de Corretagem')),
                ('taxa_custodia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxa de Custódia')),
                ('emolumentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxas da B3', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Emolumentos')),
                ('impostos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IR, IOF, etc.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impostos')),
                ('outras_taxas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Outras Taxas')),
                ('corretora', models.CharField(blank=True, help_text='Ex: Clear, Rico, XP, Binance, etc.', max_length=100, verbose_name='Corretora')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('vencido', 'Vencido')], default='ativo', max_length=10, verbose_name='Status')),
                ('data_vencimento', models.DateField(blank=True, help_text='Para ativos de renda fixa', null=True, verbose_name='Data de Vencimento')),
                ('rentabilidade_contratada', models.CharField(blank=True, help_text='Ex: 100% CDI, IPCA + 6%, 12% a.a.', max_length=100, verbose_name='Rentabilidade Contratada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investimentos', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-data_operacao', '-criado_em'],
                'indexes': [models.Index(fields=['-data_operacao'], name='investiment_data_op_e2de35_idx'), models.Index(fields=['ticker'], name='investiment_ticker_952a1a_idx'), models.Index(fields=['tipo_ativo'], name='investiment_tipo_at_d92362_idx'), models.Index(fields=['status'], name='investiment_status_c4dd8f_idx')],
            },
        ),
    ]
