# Generated by Django 6.0.1 on 2026-02-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='investimento',
            name='investiment_status_c4dd8f_idx',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='corretora',
        ),
        migrations.RemoveField(
            model_name='investimento',
            name='status',
        ),
    ]
