# Generated by Django 6.0.1 on 2026-01-30 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='valorpago',
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='contas_pagar.categoriaconta'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='contas_pagar.fornecedor'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='intervalo_personalizado',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalo em dias (se recorrência for personalizada)', null=True),
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('eh_analitica', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='contas_pagar.planodecontas')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='categoriaconta',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='contas_pagar.planodecontas'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='plano_conta',
            field=models.ForeignKey(blank=True, limit_choices_to={'eh_analitica': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contas_pagar.planodecontas'),
        ),
    ]
