# Generated by Django 6.0.1 on 2026-01-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0002_remove_contapagar_valorpago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planodecontas',
            options={},
        ),
        migrations.RemoveField(
            model_name='planodecontas',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='planodecontas',
            name='eh_analitica',
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='tipo',
            field=models.CharField(choices=[('pai', 'Pai'), ('filho', 'Filho')], default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='plano_conta',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'filho'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contas_pagar.planodecontas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planodecontas',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='contas_pagar.planodecontas'),
        ),
    ]
