# Generated by Django 6.0.1 on 2026-01-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0003_alter_planodecontas_options_and_more'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='empresa.empresa'),
        ),
        migrations.AlterModelOptions(
            name='planodecontas',
            options={'ordering': ['codigo'], 'verbose_name': 'Conta', 'verbose_name_plural': 'Plano de Contas'},
        ),
        migrations.RemoveField(
            model_name='planodecontas',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='plano_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contas_pagar.planodecontas'),
        ),
        migrations.AlterField(
            model_name='planodecontas',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='contas_pagar.planodecontas'),
        ),
        migrations.DeleteModel(
            name='CategoriaConta',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
