# Generated by Django 6.0.1 on 2026-01-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0004_remove_contapagar_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planodecontas',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='planodecontas',
            name='tipo',
            field=models.CharField(choices=[('grupo', 'Grupo'), ('conta', 'Conta')], default='conta', max_length=10),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='plano_conta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'conta'}, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contas_pagar.planodecontas'),
        ),
    ]
