# Generated by Django 6.0.1 on 2026-02-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0005_alter_planodecontas_options_planodecontas_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='recorrencia_gerada',
            field=models.BooleanField(default=False),
        ),
    ]
