# Generated by Django 6.0.1 on 2026-02-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0006_contapagar_recorrencia_gerada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Conta a pagar', 'verbose_name_plural': 'Contas a pagar'},
        ),
        migrations.AlterModelOptions(
            name='planodecontas',
            options={'ordering': ['codigo'], 'verbose_name': 'Plano de contas', 'verbose_name_plural': 'Plano de contas'},
        ),
        migrations.AddField(
            model_name='contapagar',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_geradas', to='contas_pagar.contapagar'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='quantidade_recorrencias',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de parcelas futuras a gerar', null=True),
        ),
    ]
