# Generated by Django 6.0.1 on 2026-02-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0007_alter_contapagar_options_alter_planodecontas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='intervalo_personalizado',
        ),
    ]
