# Generated by Django 6.0.1 on 2026-02-11 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0009_alter_contapagar_fornecedor'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='empresa.empresa'),
        ),
    ]
